package kw.lws.webservice;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2024-01-17T13:37:38.552+09:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://webservice.lws.kw/", name = "WsLwsWaterNow")
@XmlSeeAlso({ObjectFactory.class})
public interface WsLwsWaterNow {

    @WebMethod(operationName = "GetINSDHOUSPIPNGDGNSSCLNSG2")
    @RequestWrapper(localName = "GetINSDHOUSPIPNGDGNSSCLNSG2", targetNamespace = "http://webservice.lws.kw/", className = "kw.lws.webservice.GetINSDHOUSPIPNGDGNSSCLNSG2")
    @ResponseWrapper(localName = "GetINSDHOUSPIPNGDGNSSCLNSG2Response", targetNamespace = "http://webservice.lws.kw/", className = "kw.lws.webservice.GetINSDHOUSPIPNGDGNSSCLNSG2Response")
    @WebResult(name = "return", targetNamespace = "")
    public List<WsLwsWaterNowVo> getINSDHOUSPIPNGDGNSSCLNSG2(

        @WebParam(name = "strSVCKEY", targetNamespace = "")
        java.lang.String strSVCKEY,
        @WebParam(name = "strREGMNGRIP", targetNamespace = "")
        java.lang.String strREGMNGRIP,
        @WebParam(name = "strRQSTDTFR", targetNamespace = "")
        java.lang.String strRQSTDTFR,
        @WebParam(name = "strRQSTDTTO", targetNamespace = "")
        java.lang.String strRQSTDTTO,
        @WebParam(name = "strLASTUPDTDT", targetNamespace = "")
        java.lang.String strLASTUPDTDT
    ) throws Exception_Exception;

    @WebMethod(operationName = "GetSAFETYCNFIRM2")
    @RequestWrapper(localName = "GetSAFETYCNFIRM2", targetNamespace = "http://webservice.lws.kw/", className = "kw.lws.webservice.GetSAFETYCNFIRM2")
    @ResponseWrapper(localName = "GetSAFETYCNFIRM2Response", targetNamespace = "http://webservice.lws.kw/", className = "kw.lws.webservice.GetSAFETYCNFIRM2Response")
    @WebResult(name = "return", targetNamespace = "")
    public List<WsLwsWaterNowVo> getSAFETYCNFIRM2(

        @WebParam(name = "strSVCKEY", targetNamespace = "")
        java.lang.String strSVCKEY,
        @WebParam(name = "strREGMNGRIP", targetNamespace = "")
        java.lang.String strREGMNGRIP,
        @WebParam(name = "strRQSTDTFR", targetNamespace = "")
        java.lang.String strRQSTDTFR,
        @WebParam(name = "strRQSTDTTO", targetNamespace = "")
        java.lang.String strRQSTDTTO,
        @WebParam(name = "strLASTUPDTDT", targetNamespace = "")
        java.lang.String strLASTUPDTDT
    ) throws Exception_Exception;

    @WebMethod(operationName = "GetCSTMRADDR")
    @RequestWrapper(localName = "GetCSTMRADDR", targetNamespace = "http://webservice.lws.kw/", className = "kw.lws.webservice.GetCSTMRADDR")
    @ResponseWrapper(localName = "GetCSTMRADDRResponse", targetNamespace = "http://webservice.lws.kw/", className = "kw.lws.webservice.GetCSTMRADDRResponse")
    @WebResult(name = "return", targetNamespace = "")
    public List<WsLwsWaterNowVo> getCSTMRADDR(

        @WebParam(name = "strSVCKEY", targetNamespace = "")
        java.lang.String strSVCKEY,
        @WebParam(name = "strREGMNGRIP", targetNamespace = "")
        java.lang.String strREGMNGRIP,
        @WebParam(name = "strCSTMRNO", targetNamespace = "")
        java.lang.String strCSTMRNO
    ) throws Exception_Exception;

    @WebMethod(operationName = "GetSAFETYCNFIRM")
    @RequestWrapper(localName = "GetSAFETYCNFIRM", targetNamespace = "http://webservice.lws.kw/", className = "kw.lws.webservice.GetSAFETYCNFIRM")
    @ResponseWrapper(localName = "GetSAFETYCNFIRMResponse", targetNamespace = "http://webservice.lws.kw/", className = "kw.lws.webservice.GetSAFETYCNFIRMResponse")
    @WebResult(name = "return", targetNamespace = "")
    public List<WsLwsWaterNowVo> getSAFETYCNFIRM(

        @WebParam(name = "strSVCKEY", targetNamespace = "")
        java.lang.String strSVCKEY,
        @WebParam(name = "strREGMNGRIP", targetNamespace = "")
        java.lang.String strREGMNGRIP,
        @WebParam(name = "strWATSMPDEFR", targetNamespace = "")
        java.lang.String strWATSMPDEFR,
        @WebParam(name = "strWATSMPDETO", targetNamespace = "")
        java.lang.String strWATSMPDETO,
        @WebParam(name = "strLASTUPDTDT", targetNamespace = "")
        java.lang.String strLASTUPDTDT
    ) throws Exception_Exception;

    @WebMethod(operationName = "GetWATERRATE")
    @RequestWrapper(localName = "GetWATERRATE", targetNamespace = "http://webservice.lws.kw/", className = "kw.lws.webservice.GetWATERRATE")
    @ResponseWrapper(localName = "GetWATERRATEResponse", targetNamespace = "http://webservice.lws.kw/", className = "kw.lws.webservice.GetWATERRATEResponse")
    @WebResult(name = "return", targetNamespace = "")
    public List<WsLwsWaterNowVo> getWATERRATE(

        @WebParam(name = "strSVCKEY", targetNamespace = "")
        java.lang.String strSVCKEY,
        @WebParam(name = "strREGMNGRIP", targetNamespace = "")
        java.lang.String strREGMNGRIP,
        @WebParam(name = "strCSTMRNO", targetNamespace = "")
        java.lang.String strCSTMRNO,
        @WebParam(name = "strCSTRMNM", targetNamespace = "")
        java.lang.String strCSTRMNM,
        @WebParam(name = "strADJYM", targetNamespace = "")
        java.lang.String strADJYM
    ) throws Exception_Exception;

    @WebMethod(operationName = "GetINSDHOUSPIPNGDGNSSCLNSG")
    @RequestWrapper(localName = "GetINSDHOUSPIPNGDGNSSCLNSG", targetNamespace = "http://webservice.lws.kw/", className = "kw.lws.webservice.GetINSDHOUSPIPNGDGNSSCLNSG")
    @ResponseWrapper(localName = "GetINSDHOUSPIPNGDGNSSCLNSGResponse", targetNamespace = "http://webservice.lws.kw/", className = "kw.lws.webservice.GetINSDHOUSPIPNGDGNSSCLNSGResponse")
    @WebResult(name = "return", targetNamespace = "")
    public List<WsLwsWaterNowVo> getINSDHOUSPIPNGDGNSSCLNSG(

        @WebParam(name = "strSVCKEY", targetNamespace = "")
        java.lang.String strSVCKEY,
        @WebParam(name = "strREGMNGRIP", targetNamespace = "")
        java.lang.String strREGMNGRIP,
        @WebParam(name = "strVISITINSPCTDTFR", targetNamespace = "")
        java.lang.String strVISITINSPCTDTFR,
        @WebParam(name = "strVISITINSPCTDTTO", targetNamespace = "")
        java.lang.String strVISITINSPCTDTTO,
        @WebParam(name = "strLASTUPDTDT", targetNamespace = "")
        java.lang.String strLASTUPDTDT
    ) throws Exception_Exception;
}
