
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package kw.lws.webservice;

import java.util.logging.Logger;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2024-01-17T13:37:38.528+09:00
 * Generated source version: 4.0.3
 *
 */

@jakarta.jws.WebService(
                      serviceName = "WsLwsWaterNowService",
                      portName = "WsLwsWaterNowServicePort",
                      targetNamespace = "http://impl.webservice.lws.kw/",
                      wsdlLocation = "https://lws.kwater.or.kr/WS/wsLwsWaterNowService?wsdl",
                      endpointInterface = "kw.lws.webservice.WsLwsWaterNow")

public class WsLwsWaterNowServicePortImpl implements WsLwsWaterNow {

    private static final Logger LOG = Logger.getLogger(WsLwsWaterNowServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see kw.lws.webservice.WsLwsWaterNow#getINSDHOUSPIPNGDGNSSCLNSG2(java.lang.String strSVCKEY, java.lang.String strREGMNGRIP, java.lang.String strRQSTDTFR, java.lang.String strRQSTDTTO, java.lang.String strLASTUPDTDT)*
     */
    public java.util.List<kw.lws.webservice.WsLwsWaterNowVo> getINSDHOUSPIPNGDGNSSCLNSG2(java.lang.String strSVCKEY, java.lang.String strREGMNGRIP, java.lang.String strRQSTDTFR, java.lang.String strRQSTDTTO, java.lang.String strLASTUPDTDT) throws Exception_Exception   {
        LOG.info("Executing operation getINSDHOUSPIPNGDGNSSCLNSG2");
        System.out.println(strSVCKEY);
        System.out.println(strREGMNGRIP);
        System.out.println(strRQSTDTFR);
        System.out.println(strRQSTDTTO);
        System.out.println(strLASTUPDTDT);
        try {
            java.util.List<kw.lws.webservice.WsLwsWaterNowVo> _return = new java.util.ArrayList<kw.lws.webservice.WsLwsWaterNowVo>();
            kw.lws.webservice.WsLwsWaterNowVo _returnVal1 = new kw.lws.webservice.WsLwsWaterNowVo();
            _returnVal1.setFirstIndex(-322635880);
            _returnVal1.setLastIndex(2043216306);
            _returnVal1.setPageIndex(-1745033863);
            _returnVal1.setPageList("PageList-1712225516");
            _returnVal1.setPageSize(649332726);
            _returnVal1.setPageUnit(160679561);
            _returnVal1.setRecordCountPerPage(-1261351653);
            _returnVal1.setRnum(306228901);
            _returnVal1.setTotalCount(2107425667);
            _returnVal1.setAthrId("AthrId1674315884");
            _returnVal1.setBiznDivCd("BiznDivCd-915153515");
            _returnVal1.setChk("Chk-1981819087");
            _returnVal1.setConectIp("ConectIp1807057630");
            _returnVal1.setDeptNm("DeptNm-1719085299");
            _returnVal1.setFrstRegistDt("FrstRegistDt1929290668");
            _returnVal1.setFrstRgstrId("FrstRgstrId301783818");
            _returnVal1.setFrstRgstrIp("FrstRgstrIp769835854");
            _returnVal1.setHqNm("HqNm126945088");
            _returnVal1.setLastUpdtDt("LastUpdtDt25118634");
            _returnVal1.setLastUpdusrId("LastUpdusrId1523111028");
            _returnVal1.setLastUpdusrIp("LastUpdusrIp-790699769");
            _returnVal1.setRowStatus("RowStatus1347328498");
            _returnVal1.setSysDivCd("SysDivCd336141118");
            _returnVal1.setUsrId("UsrId-439166017");
            _returnVal1.setUsrNm("UsrNm1856811436");
            _returnVal1.setAddr("Addr1713184345");
            _returnVal1.setAdjym("Adjym138387872");
            _returnVal1.setAmt01Ago("Amt01Ago-1283172713");
            _returnVal1.setAmt12Ago("Amt12Ago-1254440171");
            _returnVal1.setBuldty("Buldty1574929261");
            _returnVal1.setCalbrcg("Calbrcg-314640904");
            _returnVal1.setClnsgdtlctnt("Clnsgdtlctnt-1740478310");
            _returnVal1.setClnsgnextntu("Clnsgnextntu1362444881");
            _returnVal1.setClnsgrstdiv("Clnsgrstdiv-274920298");
            _returnVal1.setClnsgtime("Clnsgtime-130436096");
            _returnVal1.setCstmrnm("Cstmrnm1910331691");
            _returnVal1.setCstmrno("Cstmrno2069941998");
            _returnVal1.setDgnssdtlctnt("Dgnssdtlctnt-89367130");
            _returnVal1.setDgnssrstdiv("Dgnssrstdiv343557863");
            _returnVal1.setExam1Value01("Exam1Value01389022341");
            _returnVal1.setExam1Value02("Exam1Value02-71778697");
            _returnVal1.setExam1Value03("Exam1Value03-1074867704");
            _returnVal1.setExam1Value04("Exam1Value042062533240");
            _returnVal1.setExam1Value05("Exam1Value05-815882733");
            _returnVal1.setExam1Value06("Exam1Value06-1875930051");
            _returnVal1.setExam1Value07("Exam1Value07-301100230");
            _returnVal1.setExam2Value01("Exam2Value01357345915");
            _returnVal1.setExam2Value02("Exam2Value02-1253735938");
            _returnVal1.setExam2Value03("Exam2Value03-577195686");
            _returnVal1.setExam2Value04("Exam2Value04-456318344");
            _returnVal1.setExam2Value05("Exam2Value051077955675");
            _returnVal1.setExam2Value06("Exam2Value06-878861306");
            _returnVal1.setExam2Value07("Exam2Value071143898355");
            _returnVal1.setExam2Value08("Exam2Value08-2069673543");
            _returnVal1.setExam2Value09("Exam2Value09-1648783608");
            _returnVal1.setExam2Value10("Exam2Value10-395971180");
            _returnVal1.setExam2Value11("Exam2Value11-23550788");
            _returnVal1.setExam2Value12("Exam2Value121913038814");
            _returnVal1.setExam2Value13("Exam2Value13-1918083810");
            _returnVal1.setFldevtdiv("Fldevtdiv-1887572720");
            _returnVal1.setFnctlcnm("Fnctlcnm2122966464");
            _returnVal1.setInspctdivnm("Inspctdivnm1471040553");
            _returnVal1.setLastupdt("Lastupdt1874922822");
            _returnVal1.setLayingyear("Layingyear1984876656");
            _returnVal1.setMesurede("Mesurede-1387926174");
            _returnVal1.setPipedtlknd("Pipedtlknd-1955916565");
            _returnVal1.setPipeknd("Pipeknd-2065208100");
            _returnVal1.setPrcsstatnm("Prcsstatnm-1306094319");
            _returnVal1.setRqstdt("Rqstdt2094729886");
            _returnVal1.setRstnm("Rstnm-1649687167");
            _returnVal1.setRstty("Rstty-1958915886");
            _returnVal1.setRstty2("Rstty2-1983878967");
            _returnVal1.setSeweramt("Seweramt-2133031020");
            _returnVal1.setSewerecamt("Sewerecamt391645056");
            _returnVal1.setSewerrntfee("Sewerrntfee-1957506861");
            _returnVal1.setSewerrprsindutynm("Sewerrprsindutynm-442222532");
            _returnVal1.setSewerusgqty("Sewerusgqty1194218311");
            _returnVal1.setSgccd("Sgccd-1145189585");
            _returnVal1.setTastesmellty("Tastesmellty-1311469397");
            _returnVal1.setUgrwtramt("Ugrwtramt1539819119");
            _returnVal1.setUgrwtrecamt("Ugrwtrecamt456852385");
            _returnVal1.setUgrwtrpmonguidncvu("Ugrwtrpmonguidncvu-2146452683");
            _returnVal1.setUgrwtrrntfee("Ugrwtrrntfee239516645");
            _returnVal1.setUgrwtrrprsindutynm("Ugrwtrrprsindutynm-1770968678");
            _returnVal1.setUgrwtrthsmonguidncvu("Ugrwtrthsmonguidncvu1006203834");
            _returnVal1.setUgrwtrusgqty("Ugrwtrusgqty1990899603");
            _returnVal1.setUsedt("Usedt486643637");
            _returnVal1.setVisitdt("Visitdt906215745");
            _returnVal1.setVisitinspctdt("Visitinspctdt1471644249");
            _returnVal1.setWatsmpde("Watsmpde-985429037");
            _returnVal1.setWrppamt("Wrppamt-1169502440");
            _returnVal1.setWrppcalbrnm("Wrppcalbrnm1985870213");
            _returnVal1.setWrppecamt("Wrppecamt468956346");
            _returnVal1.setWrpppmonguidncvu("Wrpppmonguidncvu1904039041");
            _returnVal1.setWrpprntfee("Wrpprntfee2088033593");
            _returnVal1.setWrpprprsindutynm("Wrpprprsindutynm-1811976265");
            _returnVal1.setWrppthsmonguidncvu("Wrppthsmonguidncvu-1679310447");
            _returnVal1.setWrppusgqty("Wrppusgqty578570202");
            _returnVal1.setWrppusgqty01Ago("Wrppusgqty01Ago497039894");
            _returnVal1.setWrppusgqty12Ago("Wrppusgqty12Ago-1064022995");
            _returnVal1.setWsppdm("Wsppdm1241663566");
            _returnVal1.setWttnkinstdiv("Wttnkinstdiv-1626352189");
            _returnVal1.setWusealltamt("Wusealltamt424684899");
            _returnVal1.setWusealltecamt("Wusealltecamt318498137");
            _returnVal1.setWusealltrntfee("Wusealltrntfee-810665821");
            _returnVal1.setWusealltrprsindutynm("Wusealltrprsindutynm-1169534212");
            _returnVal1.setWusealltusgqty("Wusealltusgqty-1732285522");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see kw.lws.webservice.WsLwsWaterNow#getSAFETYCNFIRM2(java.lang.String strSVCKEY, java.lang.String strREGMNGRIP, java.lang.String strRQSTDTFR, java.lang.String strRQSTDTTO, java.lang.String strLASTUPDTDT)*
     */
    public java.util.List<kw.lws.webservice.WsLwsWaterNowVo> getSAFETYCNFIRM2(java.lang.String strSVCKEY, java.lang.String strREGMNGRIP, java.lang.String strRQSTDTFR, java.lang.String strRQSTDTTO, java.lang.String strLASTUPDTDT) throws Exception_Exception   {
        LOG.info("Executing operation getSAFETYCNFIRM2");
        System.out.println(strSVCKEY);
        System.out.println(strREGMNGRIP);
        System.out.println(strRQSTDTFR);
        System.out.println(strRQSTDTTO);
        System.out.println(strLASTUPDTDT);
        try {
            java.util.List<kw.lws.webservice.WsLwsWaterNowVo> _return = new java.util.ArrayList<kw.lws.webservice.WsLwsWaterNowVo>();
            kw.lws.webservice.WsLwsWaterNowVo _returnVal1 = new kw.lws.webservice.WsLwsWaterNowVo();
            _returnVal1.setFirstIndex(1101922326);
            _returnVal1.setLastIndex(-2018857405);
            _returnVal1.setPageIndex(-351558763);
            _returnVal1.setPageList("PageList1224663491");
            _returnVal1.setPageSize(-1329381051);
            _returnVal1.setPageUnit(438191339);
            _returnVal1.setRecordCountPerPage(157784224);
            _returnVal1.setRnum(1907053137);
            _returnVal1.setTotalCount(-736451432);
            _returnVal1.setAthrId("AthrId1388128421");
            _returnVal1.setBiznDivCd("BiznDivCd-1507330777");
            _returnVal1.setChk("Chk816622029");
            _returnVal1.setConectIp("ConectIp-1822487379");
            _returnVal1.setDeptNm("DeptNm-519477685");
            _returnVal1.setFrstRegistDt("FrstRegistDt1614106208");
            _returnVal1.setFrstRgstrId("FrstRgstrId-650367850");
            _returnVal1.setFrstRgstrIp("FrstRgstrIp239943774");
            _returnVal1.setHqNm("HqNm757678154");
            _returnVal1.setLastUpdtDt("LastUpdtDt816921375");
            _returnVal1.setLastUpdusrId("LastUpdusrId949805913");
            _returnVal1.setLastUpdusrIp("LastUpdusrIp885778775");
            _returnVal1.setRowStatus("RowStatus-1320711256");
            _returnVal1.setSysDivCd("SysDivCd1145013899");
            _returnVal1.setUsrId("UsrId-1279006282");
            _returnVal1.setUsrNm("UsrNm1433167848");
            _returnVal1.setAddr("Addr-2077337273");
            _returnVal1.setAdjym("Adjym-173843948");
            _returnVal1.setAmt01Ago("Amt01Ago1961132835");
            _returnVal1.setAmt12Ago("Amt12Ago1459916827");
            _returnVal1.setBuldty("Buldty-1509134486");
            _returnVal1.setCalbrcg("Calbrcg1722847908");
            _returnVal1.setClnsgdtlctnt("Clnsgdtlctnt11409936");
            _returnVal1.setClnsgnextntu("Clnsgnextntu1686021129");
            _returnVal1.setClnsgrstdiv("Clnsgrstdiv-1604692104");
            _returnVal1.setClnsgtime("Clnsgtime132166932");
            _returnVal1.setCstmrnm("Cstmrnm-1219982004");
            _returnVal1.setCstmrno("Cstmrno-1778507927");
            _returnVal1.setDgnssdtlctnt("Dgnssdtlctnt-1646525440");
            _returnVal1.setDgnssrstdiv("Dgnssrstdiv-807520799");
            _returnVal1.setExam1Value01("Exam1Value01-822251609");
            _returnVal1.setExam1Value02("Exam1Value02-1655887767");
            _returnVal1.setExam1Value03("Exam1Value0367654397");
            _returnVal1.setExam1Value04("Exam1Value04-1706031073");
            _returnVal1.setExam1Value05("Exam1Value05-196928041");
            _returnVal1.setExam1Value06("Exam1Value06-965756480");
            _returnVal1.setExam1Value07("Exam1Value07200274010");
            _returnVal1.setExam2Value01("Exam2Value01-77944915");
            _returnVal1.setExam2Value02("Exam2Value02-959918433");
            _returnVal1.setExam2Value03("Exam2Value03628546051");
            _returnVal1.setExam2Value04("Exam2Value04-497984329");
            _returnVal1.setExam2Value05("Exam2Value05451613353");
            _returnVal1.setExam2Value06("Exam2Value06594608429");
            _returnVal1.setExam2Value07("Exam2Value07-1853918152");
            _returnVal1.setExam2Value08("Exam2Value082099256429");
            _returnVal1.setExam2Value09("Exam2Value09-483170778");
            _returnVal1.setExam2Value10("Exam2Value101914301891");
            _returnVal1.setExam2Value11("Exam2Value11-412244568");
            _returnVal1.setExam2Value12("Exam2Value12-459189553");
            _returnVal1.setExam2Value13("Exam2Value13-267906532");
            _returnVal1.setFldevtdiv("Fldevtdiv-907420518");
            _returnVal1.setFnctlcnm("Fnctlcnm-424766215");
            _returnVal1.setInspctdivnm("Inspctdivnm-140489293");
            _returnVal1.setLastupdt("Lastupdt1682430111");
            _returnVal1.setLayingyear("Layingyear-1714452734");
            _returnVal1.setMesurede("Mesurede207103611");
            _returnVal1.setPipedtlknd("Pipedtlknd1231144240");
            _returnVal1.setPipeknd("Pipeknd-1234695084");
            _returnVal1.setPrcsstatnm("Prcsstatnm-347806003");
            _returnVal1.setRqstdt("Rqstdt-291561022");
            _returnVal1.setRstnm("Rstnm891605928");
            _returnVal1.setRstty("Rstty-119422433");
            _returnVal1.setRstty2("Rstty21030035437");
            _returnVal1.setSeweramt("Seweramt1762761844");
            _returnVal1.setSewerecamt("Sewerecamt-2106791416");
            _returnVal1.setSewerrntfee("Sewerrntfee1708386849");
            _returnVal1.setSewerrprsindutynm("Sewerrprsindutynm877408348");
            _returnVal1.setSewerusgqty("Sewerusgqty579649123");
            _returnVal1.setSgccd("Sgccd1463829582");
            _returnVal1.setTastesmellty("Tastesmellty-2114354207");
            _returnVal1.setUgrwtramt("Ugrwtramt-423480773");
            _returnVal1.setUgrwtrecamt("Ugrwtrecamt-1513999651");
            _returnVal1.setUgrwtrpmonguidncvu("Ugrwtrpmonguidncvu-566582709");
            _returnVal1.setUgrwtrrntfee("Ugrwtrrntfee-246259256");
            _returnVal1.setUgrwtrrprsindutynm("Ugrwtrrprsindutynm-794788802");
            _returnVal1.setUgrwtrthsmonguidncvu("Ugrwtrthsmonguidncvu227728195");
            _returnVal1.setUgrwtrusgqty("Ugrwtrusgqty504121514");
            _returnVal1.setUsedt("Usedt-1160761390");
            _returnVal1.setVisitdt("Visitdt1567841350");
            _returnVal1.setVisitinspctdt("Visitinspctdt-1664510248");
            _returnVal1.setWatsmpde("Watsmpde1928957488");
            _returnVal1.setWrppamt("Wrppamt-817843838");
            _returnVal1.setWrppcalbrnm("Wrppcalbrnm-2100320177");
            _returnVal1.setWrppecamt("Wrppecamt102380506");
            _returnVal1.setWrpppmonguidncvu("Wrpppmonguidncvu-647005884");
            _returnVal1.setWrpprntfee("Wrpprntfee-37131497");
            _returnVal1.setWrpprprsindutynm("Wrpprprsindutynm116294028");
            _returnVal1.setWrppthsmonguidncvu("Wrppthsmonguidncvu-1963598378");
            _returnVal1.setWrppusgqty("Wrppusgqty1996894642");
            _returnVal1.setWrppusgqty01Ago("Wrppusgqty01Ago1423452668");
            _returnVal1.setWrppusgqty12Ago("Wrppusgqty12Ago1151313359");
            _returnVal1.setWsppdm("Wsppdm-553149128");
            _returnVal1.setWttnkinstdiv("Wttnkinstdiv1167215275");
            _returnVal1.setWusealltamt("Wusealltamt883892356");
            _returnVal1.setWusealltecamt("Wusealltecamt-1815809234");
            _returnVal1.setWusealltrntfee("Wusealltrntfee809548833");
            _returnVal1.setWusealltrprsindutynm("Wusealltrprsindutynm1852975376");
            _returnVal1.setWusealltusgqty("Wusealltusgqty-135624490");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see kw.lws.webservice.WsLwsWaterNow#getCSTMRADDR(java.lang.String strSVCKEY, java.lang.String strREGMNGRIP, java.lang.String strCSTMRNO)*
     */
    public java.util.List<kw.lws.webservice.WsLwsWaterNowVo> getCSTMRADDR(java.lang.String strSVCKEY, java.lang.String strREGMNGRIP, java.lang.String strCSTMRNO) throws Exception_Exception   {
        LOG.info("Executing operation getCSTMRADDR");
        System.out.println(strSVCKEY);
        System.out.println(strREGMNGRIP);
        System.out.println(strCSTMRNO);
        try {
            java.util.List<kw.lws.webservice.WsLwsWaterNowVo> _return = new java.util.ArrayList<kw.lws.webservice.WsLwsWaterNowVo>();
            kw.lws.webservice.WsLwsWaterNowVo _returnVal1 = new kw.lws.webservice.WsLwsWaterNowVo();
            _returnVal1.setFirstIndex(-342883869);
            _returnVal1.setLastIndex(696657021);
            _returnVal1.setPageIndex(1129646575);
            _returnVal1.setPageList("PageList701039397");
            _returnVal1.setPageSize(-203097996);
            _returnVal1.setPageUnit(-309523629);
            _returnVal1.setRecordCountPerPage(428698957);
            _returnVal1.setRnum(1491018532);
            _returnVal1.setTotalCount(198442515);
            _returnVal1.setAthrId("AthrId562462046");
            _returnVal1.setBiznDivCd("BiznDivCd-438769371");
            _returnVal1.setChk("Chk-227417927");
            _returnVal1.setConectIp("ConectIp-296947898");
            _returnVal1.setDeptNm("DeptNm1092526301");
            _returnVal1.setFrstRegistDt("FrstRegistDt-593254224");
            _returnVal1.setFrstRgstrId("FrstRgstrId1849352176");
            _returnVal1.setFrstRgstrIp("FrstRgstrIp-1706608438");
            _returnVal1.setHqNm("HqNm-934428505");
            _returnVal1.setLastUpdtDt("LastUpdtDt-1636951065");
            _returnVal1.setLastUpdusrId("LastUpdusrId-686504910");
            _returnVal1.setLastUpdusrIp("LastUpdusrIp584187061");
            _returnVal1.setRowStatus("RowStatus-1060735871");
            _returnVal1.setSysDivCd("SysDivCd1834982213");
            _returnVal1.setUsrId("UsrId1245512373");
            _returnVal1.setUsrNm("UsrNm-1675696678");
            _returnVal1.setAddr("Addr28146355");
            _returnVal1.setAdjym("Adjym1752761297");
            _returnVal1.setAmt01Ago("Amt01Ago-272897994");
            _returnVal1.setAmt12Ago("Amt12Ago-1361293968");
            _returnVal1.setBuldty("Buldty-704833831");
            _returnVal1.setCalbrcg("Calbrcg-293171365");
            _returnVal1.setClnsgdtlctnt("Clnsgdtlctnt-1168456218");
            _returnVal1.setClnsgnextntu("Clnsgnextntu-1990617355");
            _returnVal1.setClnsgrstdiv("Clnsgrstdiv-1044444682");
            _returnVal1.setClnsgtime("Clnsgtime-1222611707");
            _returnVal1.setCstmrnm("Cstmrnm-1482983007");
            _returnVal1.setCstmrno("Cstmrno674948687");
            _returnVal1.setDgnssdtlctnt("Dgnssdtlctnt224753614");
            _returnVal1.setDgnssrstdiv("Dgnssrstdiv1191042565");
            _returnVal1.setExam1Value01("Exam1Value011873003877");
            _returnVal1.setExam1Value02("Exam1Value02-449866699");
            _returnVal1.setExam1Value03("Exam1Value032050772340");
            _returnVal1.setExam1Value04("Exam1Value04-1898521944");
            _returnVal1.setExam1Value05("Exam1Value052101488129");
            _returnVal1.setExam1Value06("Exam1Value06594609356");
            _returnVal1.setExam1Value07("Exam1Value07-1066271455");
            _returnVal1.setExam2Value01("Exam2Value011833730969");
            _returnVal1.setExam2Value02("Exam2Value021985558796");
            _returnVal1.setExam2Value03("Exam2Value03-167394156");
            _returnVal1.setExam2Value04("Exam2Value04-3169465");
            _returnVal1.setExam2Value05("Exam2Value05-1525619869");
            _returnVal1.setExam2Value06("Exam2Value06-1604742632");
            _returnVal1.setExam2Value07("Exam2Value0785921669");
            _returnVal1.setExam2Value08("Exam2Value081025894629");
            _returnVal1.setExam2Value09("Exam2Value09-1794456525");
            _returnVal1.setExam2Value10("Exam2Value10-2109604056");
            _returnVal1.setExam2Value11("Exam2Value111956980341");
            _returnVal1.setExam2Value12("Exam2Value12284505884");
            _returnVal1.setExam2Value13("Exam2Value13-1732600350");
            _returnVal1.setFldevtdiv("Fldevtdiv-2128583586");
            _returnVal1.setFnctlcnm("Fnctlcnm1885935292");
            _returnVal1.setInspctdivnm("Inspctdivnm1429016578");
            _returnVal1.setLastupdt("Lastupdt-1477320653");
            _returnVal1.setLayingyear("Layingyear-58362120");
            _returnVal1.setMesurede("Mesurede-2135369703");
            _returnVal1.setPipedtlknd("Pipedtlknd-2126012234");
            _returnVal1.setPipeknd("Pipeknd1446911320");
            _returnVal1.setPrcsstatnm("Prcsstatnm17330045");
            _returnVal1.setRqstdt("Rqstdt1048372439");
            _returnVal1.setRstnm("Rstnm1791221940");
            _returnVal1.setRstty("Rstty947771579");
            _returnVal1.setRstty2("Rstty2-820565197");
            _returnVal1.setSeweramt("Seweramt651472939");
            _returnVal1.setSewerecamt("Sewerecamt-850275734");
            _returnVal1.setSewerrntfee("Sewerrntfee-2110980614");
            _returnVal1.setSewerrprsindutynm("Sewerrprsindutynm-1222479661");
            _returnVal1.setSewerusgqty("Sewerusgqty-1919312160");
            _returnVal1.setSgccd("Sgccd-1490437877");
            _returnVal1.setTastesmellty("Tastesmellty676545586");
            _returnVal1.setUgrwtramt("Ugrwtramt-1594012545");
            _returnVal1.setUgrwtrecamt("Ugrwtrecamt1250321973");
            _returnVal1.setUgrwtrpmonguidncvu("Ugrwtrpmonguidncvu-2076158046");
            _returnVal1.setUgrwtrrntfee("Ugrwtrrntfee1440678271");
            _returnVal1.setUgrwtrrprsindutynm("Ugrwtrrprsindutynm-1505642765");
            _returnVal1.setUgrwtrthsmonguidncvu("Ugrwtrthsmonguidncvu540734725");
            _returnVal1.setUgrwtrusgqty("Ugrwtrusgqty60263785");
            _returnVal1.setUsedt("Usedt-1864682813");
            _returnVal1.setVisitdt("Visitdt-1778648069");
            _returnVal1.setVisitinspctdt("Visitinspctdt-718058712");
            _returnVal1.setWatsmpde("Watsmpde-2046041253");
            _returnVal1.setWrppamt("Wrppamt-1315456089");
            _returnVal1.setWrppcalbrnm("Wrppcalbrnm-704539612");
            _returnVal1.setWrppecamt("Wrppecamt-146152679");
            _returnVal1.setWrpppmonguidncvu("Wrpppmonguidncvu854908679");
            _returnVal1.setWrpprntfee("Wrpprntfee415703775");
            _returnVal1.setWrpprprsindutynm("Wrpprprsindutynm-1418762826");
            _returnVal1.setWrppthsmonguidncvu("Wrppthsmonguidncvu-1597730344");
            _returnVal1.setWrppusgqty("Wrppusgqty-1913180506");
            _returnVal1.setWrppusgqty01Ago("Wrppusgqty01Ago1208307377");
            _returnVal1.setWrppusgqty12Ago("Wrppusgqty12Ago2065080544");
            _returnVal1.setWsppdm("Wsppdm-864747246");
            _returnVal1.setWttnkinstdiv("Wttnkinstdiv1204093551");
            _returnVal1.setWusealltamt("Wusealltamt-982579785");
            _returnVal1.setWusealltecamt("Wusealltecamt2069801781");
            _returnVal1.setWusealltrntfee("Wusealltrntfee-1285281922");
            _returnVal1.setWusealltrprsindutynm("Wusealltrprsindutynm-495311062");
            _returnVal1.setWusealltusgqty("Wusealltusgqty-1356187678");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see kw.lws.webservice.WsLwsWaterNow#getSAFETYCNFIRM(java.lang.String strSVCKEY, java.lang.String strREGMNGRIP, java.lang.String strWATSMPDEFR, java.lang.String strWATSMPDETO, java.lang.String strLASTUPDTDT)*
     */
    public java.util.List<kw.lws.webservice.WsLwsWaterNowVo> getSAFETYCNFIRM(java.lang.String strSVCKEY, java.lang.String strREGMNGRIP, java.lang.String strWATSMPDEFR, java.lang.String strWATSMPDETO, java.lang.String strLASTUPDTDT) throws Exception_Exception   {
        LOG.info("Executing operation getSAFETYCNFIRM");
        System.out.println(strSVCKEY);
        System.out.println(strREGMNGRIP);
        System.out.println(strWATSMPDEFR);
        System.out.println(strWATSMPDETO);
        System.out.println(strLASTUPDTDT);
        try {
            java.util.List<kw.lws.webservice.WsLwsWaterNowVo> _return = new java.util.ArrayList<kw.lws.webservice.WsLwsWaterNowVo>();
            kw.lws.webservice.WsLwsWaterNowVo _returnVal1 = new kw.lws.webservice.WsLwsWaterNowVo();
            _returnVal1.setFirstIndex(-1097478569);
            _returnVal1.setLastIndex(-736992375);
            _returnVal1.setPageIndex(654751235);
            _returnVal1.setPageList("PageList-2093263933");
            _returnVal1.setPageSize(-2045665807);
            _returnVal1.setPageUnit(130817076);
            _returnVal1.setRecordCountPerPage(1291087264);
            _returnVal1.setRnum(-754701307);
            _returnVal1.setTotalCount(-1088730902);
            _returnVal1.setAthrId("AthrId-131265475");
            _returnVal1.setBiznDivCd("BiznDivCd1979713653");
            _returnVal1.setChk("Chk344797501");
            _returnVal1.setConectIp("ConectIp565397974");
            _returnVal1.setDeptNm("DeptNm1273666428");
            _returnVal1.setFrstRegistDt("FrstRegistDt-1396628394");
            _returnVal1.setFrstRgstrId("FrstRgstrId-1098775578");
            _returnVal1.setFrstRgstrIp("FrstRgstrIp435890864");
            _returnVal1.setHqNm("HqNm-1868567920");
            _returnVal1.setLastUpdtDt("LastUpdtDt-1238331571");
            _returnVal1.setLastUpdusrId("LastUpdusrId-757685594");
            _returnVal1.setLastUpdusrIp("LastUpdusrIp-691318842");
            _returnVal1.setRowStatus("RowStatus-1243843398");
            _returnVal1.setSysDivCd("SysDivCd-1836708435");
            _returnVal1.setUsrId("UsrId-275072810");
            _returnVal1.setUsrNm("UsrNm635829748");
            _returnVal1.setAddr("Addr1986030600");
            _returnVal1.setAdjym("Adjym-1344017049");
            _returnVal1.setAmt01Ago("Amt01Ago-1311452863");
            _returnVal1.setAmt12Ago("Amt12Ago1066930196");
            _returnVal1.setBuldty("Buldty1300247477");
            _returnVal1.setCalbrcg("Calbrcg1373108891");
            _returnVal1.setClnsgdtlctnt("Clnsgdtlctnt1939304746");
            _returnVal1.setClnsgnextntu("Clnsgnextntu195760052");
            _returnVal1.setClnsgrstdiv("Clnsgrstdiv844799183");
            _returnVal1.setClnsgtime("Clnsgtime555657586");
            _returnVal1.setCstmrnm("Cstmrnm1092509587");
            _returnVal1.setCstmrno("Cstmrno2006164746");
            _returnVal1.setDgnssdtlctnt("Dgnssdtlctnt-819738342");
            _returnVal1.setDgnssrstdiv("Dgnssrstdiv-527529686");
            _returnVal1.setExam1Value01("Exam1Value01-656237380");
            _returnVal1.setExam1Value02("Exam1Value02352490020");
            _returnVal1.setExam1Value03("Exam1Value03-226437068");
            _returnVal1.setExam1Value04("Exam1Value04-471903118");
            _returnVal1.setExam1Value05("Exam1Value05-59257367");
            _returnVal1.setExam1Value06("Exam1Value06-944919197");
            _returnVal1.setExam1Value07("Exam1Value07-1710308615");
            _returnVal1.setExam2Value01("Exam2Value01-1402916105");
            _returnVal1.setExam2Value02("Exam2Value02-1678892696");
            _returnVal1.setExam2Value03("Exam2Value03-594964695");
            _returnVal1.setExam2Value04("Exam2Value04-504297176");
            _returnVal1.setExam2Value05("Exam2Value051676542014");
            _returnVal1.setExam2Value06("Exam2Value06396357330");
            _returnVal1.setExam2Value07("Exam2Value07-2096896303");
            _returnVal1.setExam2Value08("Exam2Value08-202697402");
            _returnVal1.setExam2Value09("Exam2Value091218948020");
            _returnVal1.setExam2Value10("Exam2Value10352491408");
            _returnVal1.setExam2Value11("Exam2Value11-2057721121");
            _returnVal1.setExam2Value12("Exam2Value122068937410");
            _returnVal1.setExam2Value13("Exam2Value131236534786");
            _returnVal1.setFldevtdiv("Fldevtdiv377908129");
            _returnVal1.setFnctlcnm("Fnctlcnm-148662152");
            _returnVal1.setInspctdivnm("Inspctdivnm1213100633");
            _returnVal1.setLastupdt("Lastupdt2002227110");
            _returnVal1.setLayingyear("Layingyear352949913");
            _returnVal1.setMesurede("Mesurede-1008290284");
            _returnVal1.setPipedtlknd("Pipedtlknd1858549948");
            _returnVal1.setPipeknd("Pipeknd-1261036353");
            _returnVal1.setPrcsstatnm("Prcsstatnm-283223828");
            _returnVal1.setRqstdt("Rqstdt-367145615");
            _returnVal1.setRstnm("Rstnm-236571793");
            _returnVal1.setRstty("Rstty-1718001113");
            _returnVal1.setRstty2("Rstty21336217964");
            _returnVal1.setSeweramt("Seweramt1292636362");
            _returnVal1.setSewerecamt("Sewerecamt-1087897613");
            _returnVal1.setSewerrntfee("Sewerrntfee1049280454");
            _returnVal1.setSewerrprsindutynm("Sewerrprsindutynm641653520");
            _returnVal1.setSewerusgqty("Sewerusgqty1610112840");
            _returnVal1.setSgccd("Sgccd-1995976409");
            _returnVal1.setTastesmellty("Tastesmellty93248549");
            _returnVal1.setUgrwtramt("Ugrwtramt1764082422");
            _returnVal1.setUgrwtrecamt("Ugrwtrecamt863231161");
            _returnVal1.setUgrwtrpmonguidncvu("Ugrwtrpmonguidncvu-867582230");
            _returnVal1.setUgrwtrrntfee("Ugrwtrrntfee1088873793");
            _returnVal1.setUgrwtrrprsindutynm("Ugrwtrrprsindutynm1430510250");
            _returnVal1.setUgrwtrthsmonguidncvu("Ugrwtrthsmonguidncvu1212534911");
            _returnVal1.setUgrwtrusgqty("Ugrwtrusgqty-1448612859");
            _returnVal1.setUsedt("Usedt405047969");
            _returnVal1.setVisitdt("Visitdt-13456728");
            _returnVal1.setVisitinspctdt("Visitinspctdt-691929142");
            _returnVal1.setWatsmpde("Watsmpde445752904");
            _returnVal1.setWrppamt("Wrppamt-1919220566");
            _returnVal1.setWrppcalbrnm("Wrppcalbrnm-899626721");
            _returnVal1.setWrppecamt("Wrppecamt1139668745");
            _returnVal1.setWrpppmonguidncvu("Wrpppmonguidncvu-1594235662");
            _returnVal1.setWrpprntfee("Wrpprntfee453557554");
            _returnVal1.setWrpprprsindutynm("Wrpprprsindutynm1261672695");
            _returnVal1.setWrppthsmonguidncvu("Wrppthsmonguidncvu1261237917");
            _returnVal1.setWrppusgqty("Wrppusgqty-903558827");
            _returnVal1.setWrppusgqty01Ago("Wrppusgqty01Ago-740659886");
            _returnVal1.setWrppusgqty12Ago("Wrppusgqty12Ago-2116586219");
            _returnVal1.setWsppdm("Wsppdm-361662769");
            _returnVal1.setWttnkinstdiv("Wttnkinstdiv2033845690");
            _returnVal1.setWusealltamt("Wusealltamt1075954816");
            _returnVal1.setWusealltecamt("Wusealltecamt231787485");
            _returnVal1.setWusealltrntfee("Wusealltrntfee-1955694844");
            _returnVal1.setWusealltrprsindutynm("Wusealltrprsindutynm-631484799");
            _returnVal1.setWusealltusgqty("Wusealltusgqty1919347932");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see kw.lws.webservice.WsLwsWaterNow#getWATERRATE(java.lang.String strSVCKEY, java.lang.String strREGMNGRIP, java.lang.String strCSTMRNO, java.lang.String strCSTRMNM, java.lang.String strADJYM)*
     */
    public java.util.List<kw.lws.webservice.WsLwsWaterNowVo> getWATERRATE(java.lang.String strSVCKEY, java.lang.String strREGMNGRIP, java.lang.String strCSTMRNO, java.lang.String strCSTRMNM, java.lang.String strADJYM) throws Exception_Exception   {
        LOG.info("Executing operation getWATERRATE");
        System.out.println(strSVCKEY);
        System.out.println(strREGMNGRIP);
        System.out.println(strCSTMRNO);
        System.out.println(strCSTRMNM);
        System.out.println(strADJYM);
        try {
            java.util.List<kw.lws.webservice.WsLwsWaterNowVo> _return = new java.util.ArrayList<kw.lws.webservice.WsLwsWaterNowVo>();
            kw.lws.webservice.WsLwsWaterNowVo _returnVal1 = new kw.lws.webservice.WsLwsWaterNowVo();
            _returnVal1.setFirstIndex(-1970999560);
            _returnVal1.setLastIndex(-718140369);
            _returnVal1.setPageIndex(1751398796);
            _returnVal1.setPageList("PageList85819593");
            _returnVal1.setPageSize(1259969366);
            _returnVal1.setPageUnit(1513480838);
            _returnVal1.setRecordCountPerPage(-2007027746);
            _returnVal1.setRnum(1476052415);
            _returnVal1.setTotalCount(74874230);
            _returnVal1.setAthrId("AthrId1049208439");
            _returnVal1.setBiznDivCd("BiznDivCd-1126607490");
            _returnVal1.setChk("Chk1257521246");
            _returnVal1.setConectIp("ConectIp-14404123");
            _returnVal1.setDeptNm("DeptNm1938196701");
            _returnVal1.setFrstRegistDt("FrstRegistDt1375964065");
            _returnVal1.setFrstRgstrId("FrstRgstrId-510986809");
            _returnVal1.setFrstRgstrIp("FrstRgstrIp1282974211");
            _returnVal1.setHqNm("HqNm834294383");
            _returnVal1.setLastUpdtDt("LastUpdtDt20246791");
            _returnVal1.setLastUpdusrId("LastUpdusrId1316548135");
            _returnVal1.setLastUpdusrIp("LastUpdusrIp1530424588");
            _returnVal1.setRowStatus("RowStatus-1851016584");
            _returnVal1.setSysDivCd("SysDivCd1750697125");
            _returnVal1.setUsrId("UsrId1528548500");
            _returnVal1.setUsrNm("UsrNm-1814942378");
            _returnVal1.setAddr("Addr536933580");
            _returnVal1.setAdjym("Adjym919981699");
            _returnVal1.setAmt01Ago("Amt01Ago2018545691");
            _returnVal1.setAmt12Ago("Amt12Ago1272418775");
            _returnVal1.setBuldty("Buldty-726881542");
            _returnVal1.setCalbrcg("Calbrcg-1484672281");
            _returnVal1.setClnsgdtlctnt("Clnsgdtlctnt-450768359");
            _returnVal1.setClnsgnextntu("Clnsgnextntu396190698");
            _returnVal1.setClnsgrstdiv("Clnsgrstdiv777311422");
            _returnVal1.setClnsgtime("Clnsgtime-1260727373");
            _returnVal1.setCstmrnm("Cstmrnm-1410656823");
            _returnVal1.setCstmrno("Cstmrno3367250");
            _returnVal1.setDgnssdtlctnt("Dgnssdtlctnt1315578809");
            _returnVal1.setDgnssrstdiv("Dgnssrstdiv2075206667");
            _returnVal1.setExam1Value01("Exam1Value0194960926");
            _returnVal1.setExam1Value02("Exam1Value021735471742");
            _returnVal1.setExam1Value03("Exam1Value03-1231161757");
            _returnVal1.setExam1Value04("Exam1Value041872138810");
            _returnVal1.setExam1Value05("Exam1Value051448572627");
            _returnVal1.setExam1Value06("Exam1Value06-337247986");
            _returnVal1.setExam1Value07("Exam1Value07-791673280");
            _returnVal1.setExam2Value01("Exam2Value011971645397");
            _returnVal1.setExam2Value02("Exam2Value02431765951");
            _returnVal1.setExam2Value03("Exam2Value03-1353944426");
            _returnVal1.setExam2Value04("Exam2Value041181500753");
            _returnVal1.setExam2Value05("Exam2Value05716922913");
            _returnVal1.setExam2Value06("Exam2Value06-15916691");
            _returnVal1.setExam2Value07("Exam2Value071140657056");
            _returnVal1.setExam2Value08("Exam2Value08-1631281459");
            _returnVal1.setExam2Value09("Exam2Value09-1308146511");
            _returnVal1.setExam2Value10("Exam2Value10818364396");
            _returnVal1.setExam2Value11("Exam2Value11-990560521");
            _returnVal1.setExam2Value12("Exam2Value12-596013296");
            _returnVal1.setExam2Value13("Exam2Value131589772371");
            _returnVal1.setFldevtdiv("Fldevtdiv-2046510878");
            _returnVal1.setFnctlcnm("Fnctlcnm1219079458");
            _returnVal1.setInspctdivnm("Inspctdivnm1270859475");
            _returnVal1.setLastupdt("Lastupdt-1526185939");
            _returnVal1.setLayingyear("Layingyear-1729316377");
            _returnVal1.setMesurede("Mesurede-851552210");
            _returnVal1.setPipedtlknd("Pipedtlknd1166036381");
            _returnVal1.setPipeknd("Pipeknd1749867298");
            _returnVal1.setPrcsstatnm("Prcsstatnm-1950735345");
            _returnVal1.setRqstdt("Rqstdt-987246671");
            _returnVal1.setRstnm("Rstnm-382478471");
            _returnVal1.setRstty("Rstty1185679225");
            _returnVal1.setRstty2("Rstty2-2004174136");
            _returnVal1.setSeweramt("Seweramt-1444636406");
            _returnVal1.setSewerecamt("Sewerecamt1076969961");
            _returnVal1.setSewerrntfee("Sewerrntfee-292960576");
            _returnVal1.setSewerrprsindutynm("Sewerrprsindutynm-1192104985");
            _returnVal1.setSewerusgqty("Sewerusgqty263084013");
            _returnVal1.setSgccd("Sgccd-1674417126");
            _returnVal1.setTastesmellty("Tastesmellty525380590");
            _returnVal1.setUgrwtramt("Ugrwtramt-563641092");
            _returnVal1.setUgrwtrecamt("Ugrwtrecamt83262238");
            _returnVal1.setUgrwtrpmonguidncvu("Ugrwtrpmonguidncvu2136071768");
            _returnVal1.setUgrwtrrntfee("Ugrwtrrntfee1272209351");
            _returnVal1.setUgrwtrrprsindutynm("Ugrwtrrprsindutynm-1118049811");
            _returnVal1.setUgrwtrthsmonguidncvu("Ugrwtrthsmonguidncvu2071622012");
            _returnVal1.setUgrwtrusgqty("Ugrwtrusgqty-654904124");
            _returnVal1.setUsedt("Usedt791512964");
            _returnVal1.setVisitdt("Visitdt-415194942");
            _returnVal1.setVisitinspctdt("Visitinspctdt-1158173888");
            _returnVal1.setWatsmpde("Watsmpde-1202880189");
            _returnVal1.setWrppamt("Wrppamt706408882");
            _returnVal1.setWrppcalbrnm("Wrppcalbrnm-445823299");
            _returnVal1.setWrppecamt("Wrppecamt-1622676601");
            _returnVal1.setWrpppmonguidncvu("Wrpppmonguidncvu-851371847");
            _returnVal1.setWrpprntfee("Wrpprntfee961424730");
            _returnVal1.setWrpprprsindutynm("Wrpprprsindutynm1958101677");
            _returnVal1.setWrppthsmonguidncvu("Wrppthsmonguidncvu-1724731891");
            _returnVal1.setWrppusgqty("Wrppusgqty-1413251210");
            _returnVal1.setWrppusgqty01Ago("Wrppusgqty01Ago1925705569");
            _returnVal1.setWrppusgqty12Ago("Wrppusgqty12Ago420202627");
            _returnVal1.setWsppdm("Wsppdm180921658");
            _returnVal1.setWttnkinstdiv("Wttnkinstdiv-173479696");
            _returnVal1.setWusealltamt("Wusealltamt-1949636046");
            _returnVal1.setWusealltecamt("Wusealltecamt1456276005");
            _returnVal1.setWusealltrntfee("Wusealltrntfee-504720286");
            _returnVal1.setWusealltrprsindutynm("Wusealltrprsindutynm2094792370");
            _returnVal1.setWusealltusgqty("Wusealltusgqty674364313");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see kw.lws.webservice.WsLwsWaterNow#getINSDHOUSPIPNGDGNSSCLNSG(java.lang.String strSVCKEY, java.lang.String strREGMNGRIP, java.lang.String strVISITINSPCTDTFR, java.lang.String strVISITINSPCTDTTO, java.lang.String strLASTUPDTDT)*
     */
    public java.util.List<kw.lws.webservice.WsLwsWaterNowVo> getINSDHOUSPIPNGDGNSSCLNSG(java.lang.String strSVCKEY, java.lang.String strREGMNGRIP, java.lang.String strVISITINSPCTDTFR, java.lang.String strVISITINSPCTDTTO, java.lang.String strLASTUPDTDT) throws Exception_Exception   {
        LOG.info("Executing operation getINSDHOUSPIPNGDGNSSCLNSG");
        System.out.println(strSVCKEY);
        System.out.println(strREGMNGRIP);
        System.out.println(strVISITINSPCTDTFR);
        System.out.println(strVISITINSPCTDTTO);
        System.out.println(strLASTUPDTDT);
        try {
            java.util.List<kw.lws.webservice.WsLwsWaterNowVo> _return = new java.util.ArrayList<kw.lws.webservice.WsLwsWaterNowVo>();
            kw.lws.webservice.WsLwsWaterNowVo _returnVal1 = new kw.lws.webservice.WsLwsWaterNowVo();
            _returnVal1.setFirstIndex(-303795838);
            _returnVal1.setLastIndex(99420745);
            _returnVal1.setPageIndex(1968628372);
            _returnVal1.setPageList("PageList-111094542");
            _returnVal1.setPageSize(1988091877);
            _returnVal1.setPageUnit(-866205724);
            _returnVal1.setRecordCountPerPage(-1150443476);
            _returnVal1.setRnum(-1126923902);
            _returnVal1.setTotalCount(965176974);
            _returnVal1.setAthrId("AthrId-1123049626");
            _returnVal1.setBiznDivCd("BiznDivCd-1966489212");
            _returnVal1.setChk("Chk1523281700");
            _returnVal1.setConectIp("ConectIp1696373886");
            _returnVal1.setDeptNm("DeptNm1121105786");
            _returnVal1.setFrstRegistDt("FrstRegistDt1010694924");
            _returnVal1.setFrstRgstrId("FrstRgstrId47373607");
            _returnVal1.setFrstRgstrIp("FrstRgstrIp950228370");
            _returnVal1.setHqNm("HqNm-850026804");
            _returnVal1.setLastUpdtDt("LastUpdtDt1737761490");
            _returnVal1.setLastUpdusrId("LastUpdusrId-1736321674");
            _returnVal1.setLastUpdusrIp("LastUpdusrIp828661459");
            _returnVal1.setRowStatus("RowStatus1963723725");
            _returnVal1.setSysDivCd("SysDivCd971433712");
            _returnVal1.setUsrId("UsrId-595061767");
            _returnVal1.setUsrNm("UsrNm-235293684");
            _returnVal1.setAddr("Addr2094441655");
            _returnVal1.setAdjym("Adjym-1002703036");
            _returnVal1.setAmt01Ago("Amt01Ago-273055685");
            _returnVal1.setAmt12Ago("Amt12Ago-1196774757");
            _returnVal1.setBuldty("Buldty1912097743");
            _returnVal1.setCalbrcg("Calbrcg1076532838");
            _returnVal1.setClnsgdtlctnt("Clnsgdtlctnt1831148877");
            _returnVal1.setClnsgnextntu("Clnsgnextntu-186192500");
            _returnVal1.setClnsgrstdiv("Clnsgrstdiv173894633");
            _returnVal1.setClnsgtime("Clnsgtime-995768874");
            _returnVal1.setCstmrnm("Cstmrnm-539978775");
            _returnVal1.setCstmrno("Cstmrno2003609315");
            _returnVal1.setDgnssdtlctnt("Dgnssdtlctnt-546502351");
            _returnVal1.setDgnssrstdiv("Dgnssrstdiv314605941");
            _returnVal1.setExam1Value01("Exam1Value01-1499481383");
            _returnVal1.setExam1Value02("Exam1Value02-191403464");
            _returnVal1.setExam1Value03("Exam1Value031758698023");
            _returnVal1.setExam1Value04("Exam1Value04615890486");
            _returnVal1.setExam1Value05("Exam1Value05-276708967");
            _returnVal1.setExam1Value06("Exam1Value06303740041");
            _returnVal1.setExam1Value07("Exam1Value07322170091");
            _returnVal1.setExam2Value01("Exam2Value01400891925");
            _returnVal1.setExam2Value02("Exam2Value02-1200365253");
            _returnVal1.setExam2Value03("Exam2Value03172234059");
            _returnVal1.setExam2Value04("Exam2Value041789566138");
            _returnVal1.setExam2Value05("Exam2Value05806394695");
            _returnVal1.setExam2Value06("Exam2Value061132705674");
            _returnVal1.setExam2Value07("Exam2Value071812878530");
            _returnVal1.setExam2Value08("Exam2Value081154800568");
            _returnVal1.setExam2Value09("Exam2Value09-835291982");
            _returnVal1.setExam2Value10("Exam2Value10284799090");
            _returnVal1.setExam2Value11("Exam2Value11-1710216302");
            _returnVal1.setExam2Value12("Exam2Value12-640445201");
            _returnVal1.setExam2Value13("Exam2Value13-1155115617");
            _returnVal1.setFldevtdiv("Fldevtdiv-764010081");
            _returnVal1.setFnctlcnm("Fnctlcnm669409173");
            _returnVal1.setInspctdivnm("Inspctdivnm1271933591");
            _returnVal1.setLastupdt("Lastupdt2091345581");
            _returnVal1.setLayingyear("Layingyear1498545251");
            _returnVal1.setMesurede("Mesurede-278767123");
            _returnVal1.setPipedtlknd("Pipedtlknd957895831");
            _returnVal1.setPipeknd("Pipeknd787523080");
            _returnVal1.setPrcsstatnm("Prcsstatnm-599901732");
            _returnVal1.setRqstdt("Rqstdt-641496483");
            _returnVal1.setRstnm("Rstnm1648026443");
            _returnVal1.setRstty("Rstty-1701581605");
            _returnVal1.setRstty2("Rstty2304833877");
            _returnVal1.setSeweramt("Seweramt-1496110124");
            _returnVal1.setSewerecamt("Sewerecamt-202937720");
            _returnVal1.setSewerrntfee("Sewerrntfee-1139845118");
            _returnVal1.setSewerrprsindutynm("Sewerrprsindutynm758442220");
            _returnVal1.setSewerusgqty("Sewerusgqty153042506");
            _returnVal1.setSgccd("Sgccd-1343285028");
            _returnVal1.setTastesmellty("Tastesmellty1698695172");
            _returnVal1.setUgrwtramt("Ugrwtramt1038221429");
            _returnVal1.setUgrwtrecamt("Ugrwtrecamt-452277809");
            _returnVal1.setUgrwtrpmonguidncvu("Ugrwtrpmonguidncvu-1847247078");
            _returnVal1.setUgrwtrrntfee("Ugrwtrrntfee-181638080");
            _returnVal1.setUgrwtrrprsindutynm("Ugrwtrrprsindutynm-1614252386");
            _returnVal1.setUgrwtrthsmonguidncvu("Ugrwtrthsmonguidncvu1563868897");
            _returnVal1.setUgrwtrusgqty("Ugrwtrusgqty-155038700");
            _returnVal1.setUsedt("Usedt-1219785371");
            _returnVal1.setVisitdt("Visitdt-759459757");
            _returnVal1.setVisitinspctdt("Visitinspctdt724043773");
            _returnVal1.setWatsmpde("Watsmpde466895018");
            _returnVal1.setWrppamt("Wrppamt1674709799");
            _returnVal1.setWrppcalbrnm("Wrppcalbrnm1098107491");
            _returnVal1.setWrppecamt("Wrppecamt-196829064");
            _returnVal1.setWrpppmonguidncvu("Wrpppmonguidncvu-1804345341");
            _returnVal1.setWrpprntfee("Wrpprntfee2112143663");
            _returnVal1.setWrpprprsindutynm("Wrpprprsindutynm-2042475165");
            _returnVal1.setWrppthsmonguidncvu("Wrppthsmonguidncvu1384825998");
            _returnVal1.setWrppusgqty("Wrppusgqty1067851802");
            _returnVal1.setWrppusgqty01Ago("Wrppusgqty01Ago639387474");
            _returnVal1.setWrppusgqty12Ago("Wrppusgqty12Ago2049784786");
            _returnVal1.setWsppdm("Wsppdm-217936197");
            _returnVal1.setWttnkinstdiv("Wttnkinstdiv860200572");
            _returnVal1.setWusealltamt("Wusealltamt381927685");
            _returnVal1.setWusealltecamt("Wusealltecamt-520077698");
            _returnVal1.setWusealltrntfee("Wusealltrntfee-618949047");
            _returnVal1.setWusealltrprsindutynm("Wusealltrprsindutynm-372761265");
            _returnVal1.setWusealltusgqty("Wusealltusgqty1190178832");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

}
