
package kw.lws.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import kw.lws.webservice.impl.WsLwsWaterNowService;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2024-01-17T13:37:38.429+09:00
 * Generated source version: 4.0.3
 *
 */
public final class WsLwsWaterNow_WsLwsWaterNowServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webservice.lws.kw/", "WsLwsWaterNowService");

    private WsLwsWaterNow_WsLwsWaterNowServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WsLwsWaterNowService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        WsLwsWaterNowService ss = new WsLwsWaterNowService(wsdlURL, SERVICE_NAME);
        WsLwsWaterNow port = ss.getWsLwsWaterNowServicePort();

        {
        System.out.println("Invoking getINSDHOUSPIPNGDGNSSCLNSG2...");
        java.lang.String _getINSDHOUSPIPNGDGNSSCLNSG2_strSVCKEY = "_getINSDHOUSPIPNGDGNSSCLNSG2_strSVCKEY1845193838";
        java.lang.String _getINSDHOUSPIPNGDGNSSCLNSG2_strREGMNGRIP = "_getINSDHOUSPIPNGDGNSSCLNSG2_strREGMNGRIP1739005059";
        java.lang.String _getINSDHOUSPIPNGDGNSSCLNSG2_strRQSTDTFR = "_getINSDHOUSPIPNGDGNSSCLNSG2_strRQSTDTFR-347699995";
        java.lang.String _getINSDHOUSPIPNGDGNSSCLNSG2_strRQSTDTTO = "_getINSDHOUSPIPNGDGNSSCLNSG2_strRQSTDTTO812023103";
        java.lang.String _getINSDHOUSPIPNGDGNSSCLNSG2_strLASTUPDTDT = "_getINSDHOUSPIPNGDGNSSCLNSG2_strLASTUPDTDT898171120";
        try {
            java.util.List<kw.lws.webservice.WsLwsWaterNowVo> _getINSDHOUSPIPNGDGNSSCLNSG2__return = port.getINSDHOUSPIPNGDGNSSCLNSG2(_getINSDHOUSPIPNGDGNSSCLNSG2_strSVCKEY, _getINSDHOUSPIPNGDGNSSCLNSG2_strREGMNGRIP, _getINSDHOUSPIPNGDGNSSCLNSG2_strRQSTDTFR, _getINSDHOUSPIPNGDGNSSCLNSG2_strRQSTDTTO, _getINSDHOUSPIPNGDGNSSCLNSG2_strLASTUPDTDT);
            System.out.println("getINSDHOUSPIPNGDGNSSCLNSG2.result=" + _getINSDHOUSPIPNGDGNSSCLNSG2__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getSAFETYCNFIRM2...");
        java.lang.String _getSAFETYCNFIRM2_strSVCKEY = "_getSAFETYCNFIRM2_strSVCKEY-517262204";
        java.lang.String _getSAFETYCNFIRM2_strREGMNGRIP = "_getSAFETYCNFIRM2_strREGMNGRIP-147791072";
        java.lang.String _getSAFETYCNFIRM2_strRQSTDTFR = "_getSAFETYCNFIRM2_strRQSTDTFR536206640";
        java.lang.String _getSAFETYCNFIRM2_strRQSTDTTO = "_getSAFETYCNFIRM2_strRQSTDTTO1775367393";
        java.lang.String _getSAFETYCNFIRM2_strLASTUPDTDT = "_getSAFETYCNFIRM2_strLASTUPDTDT-1318394367";
        try {
            java.util.List<kw.lws.webservice.WsLwsWaterNowVo> _getSAFETYCNFIRM2__return = port.getSAFETYCNFIRM2(_getSAFETYCNFIRM2_strSVCKEY, _getSAFETYCNFIRM2_strREGMNGRIP, _getSAFETYCNFIRM2_strRQSTDTFR, _getSAFETYCNFIRM2_strRQSTDTTO, _getSAFETYCNFIRM2_strLASTUPDTDT);
            System.out.println("getSAFETYCNFIRM2.result=" + _getSAFETYCNFIRM2__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getCSTMRADDR...");
        java.lang.String _getCSTMRADDR_strSVCKEY = "_getCSTMRADDR_strSVCKEY429151414";
        java.lang.String _getCSTMRADDR_strREGMNGRIP = "_getCSTMRADDR_strREGMNGRIP660262059";
        java.lang.String _getCSTMRADDR_strCSTMRNO = "_getCSTMRADDR_strCSTMRNO2134356662";
        try {
            java.util.List<kw.lws.webservice.WsLwsWaterNowVo> _getCSTMRADDR__return = port.getCSTMRADDR(_getCSTMRADDR_strSVCKEY, _getCSTMRADDR_strREGMNGRIP, _getCSTMRADDR_strCSTMRNO);
            System.out.println("getCSTMRADDR.result=" + _getCSTMRADDR__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getSAFETYCNFIRM...");
        java.lang.String _getSAFETYCNFIRM_strSVCKEY = "_getSAFETYCNFIRM_strSVCKEY-1663216025";
        java.lang.String _getSAFETYCNFIRM_strREGMNGRIP = "_getSAFETYCNFIRM_strREGMNGRIP-1891658293";
        java.lang.String _getSAFETYCNFIRM_strWATSMPDEFR = "_getSAFETYCNFIRM_strWATSMPDEFR293425021";
        java.lang.String _getSAFETYCNFIRM_strWATSMPDETO = "_getSAFETYCNFIRM_strWATSMPDETO-1280546640";
        java.lang.String _getSAFETYCNFIRM_strLASTUPDTDT = "_getSAFETYCNFIRM_strLASTUPDTDT709986966";
        try {
            java.util.List<kw.lws.webservice.WsLwsWaterNowVo> _getSAFETYCNFIRM__return = port.getSAFETYCNFIRM(_getSAFETYCNFIRM_strSVCKEY, _getSAFETYCNFIRM_strREGMNGRIP, _getSAFETYCNFIRM_strWATSMPDEFR, _getSAFETYCNFIRM_strWATSMPDETO, _getSAFETYCNFIRM_strLASTUPDTDT);
            System.out.println("getSAFETYCNFIRM.result=" + _getSAFETYCNFIRM__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getWATERRATE...");
        java.lang.String _getWATERRATE_strSVCKEY = "_getWATERRATE_strSVCKEY-224416818";
        java.lang.String _getWATERRATE_strREGMNGRIP = "_getWATERRATE_strREGMNGRIP1942141401";
        java.lang.String _getWATERRATE_strCSTMRNO = "_getWATERRATE_strCSTMRNO-1186786975";
        java.lang.String _getWATERRATE_strCSTRMNM = "_getWATERRATE_strCSTRMNM-73883876";
        java.lang.String _getWATERRATE_strADJYM = "_getWATERRATE_strADJYM-760706155";
        try {
            java.util.List<kw.lws.webservice.WsLwsWaterNowVo> _getWATERRATE__return = port.getWATERRATE(_getWATERRATE_strSVCKEY, _getWATERRATE_strREGMNGRIP, _getWATERRATE_strCSTMRNO, _getWATERRATE_strCSTRMNM, _getWATERRATE_strADJYM);
            System.out.println("getWATERRATE.result=" + _getWATERRATE__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getINSDHOUSPIPNGDGNSSCLNSG...");
        java.lang.String _getINSDHOUSPIPNGDGNSSCLNSG_strSVCKEY = "_getINSDHOUSPIPNGDGNSSCLNSG_strSVCKEY1435551155";
        java.lang.String _getINSDHOUSPIPNGDGNSSCLNSG_strREGMNGRIP = "_getINSDHOUSPIPNGDGNSSCLNSG_strREGMNGRIP1335427183";
        java.lang.String _getINSDHOUSPIPNGDGNSSCLNSG_strVISITINSPCTDTFR = "_getINSDHOUSPIPNGDGNSSCLNSG_strVISITINSPCTDTFR-1331769434";
        java.lang.String _getINSDHOUSPIPNGDGNSSCLNSG_strVISITINSPCTDTTO = "_getINSDHOUSPIPNGDGNSSCLNSG_strVISITINSPCTDTTO1478458822";
        java.lang.String _getINSDHOUSPIPNGDGNSSCLNSG_strLASTUPDTDT = "_getINSDHOUSPIPNGDGNSSCLNSG_strLASTUPDTDT-1420023474";
        try {
            java.util.List<kw.lws.webservice.WsLwsWaterNowVo> _getINSDHOUSPIPNGDGNSSCLNSG__return = port.getINSDHOUSPIPNGDGNSSCLNSG(_getINSDHOUSPIPNGDGNSSCLNSG_strSVCKEY, _getINSDHOUSPIPNGDGNSSCLNSG_strREGMNGRIP, _getINSDHOUSPIPNGDGNSSCLNSG_strVISITINSPCTDTFR, _getINSDHOUSPIPNGDGNSSCLNSG_strVISITINSPCTDTTO, _getINSDHOUSPIPNGDGNSSCLNSG_strLASTUPDTDT);
            System.out.println("getINSDHOUSPIPNGDGNSSCLNSG.result=" + _getINSDHOUSPIPNGDGNSSCLNSG__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
