package kw.lws.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import kw.lws.webservice.WsLwsWaterNow;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2024-01-17T13:37:38.560+09:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "WsLwsWaterNowService",
                  wsdlLocation = "https://lws.kwater.or.kr/WS/wsLwsWaterNowService?wsdl",
                  targetNamespace = "http://impl.webservice.lws.kw/")
public class WsLwsWaterNowService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.lws.kw/", "WsLwsWaterNowService");
    public final static QName WsLwsWaterNowServicePort = new QName("http://impl.webservice.lws.kw/", "WsLwsWaterNowServicePort");
    static {
        URL url = null;
        try {
            url = new URL("https://lws.kwater.or.kr/WS/wsLwsWaterNowService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsLwsWaterNowService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://lws.kwater.or.kr/WS/wsLwsWaterNowService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsLwsWaterNowService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsLwsWaterNowService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsLwsWaterNowService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WsLwsWaterNowService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WsLwsWaterNowService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WsLwsWaterNowService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WsLwsWaterNow
     */
    @WebEndpoint(name = "WsLwsWaterNowServicePort")
    public WsLwsWaterNow getWsLwsWaterNowServicePort() {
        return super.getPort(WsLwsWaterNowServicePort, WsLwsWaterNow.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsLwsWaterNow
     */
    @WebEndpoint(name = "WsLwsWaterNowServicePort")
    public WsLwsWaterNow getWsLwsWaterNowServicePort(WebServiceFeature... features) {
        return super.getPort(WsLwsWaterNowServicePort, WsLwsWaterNow.class, features);
    }

}
